name: Application CI
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Run backend test
        run: |
          chmod +x mvnw
          ./mvnw -ntp clean verify
      - name: Package application
        run: ./mvnw -ntp package -Pprod -DskipTests
  micro-frontends:
    name: ${{ matrix.entity }} ${{ matrix.widget }} micro frontend
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        entity: [ conference ]
        widget: [ detailsWidget, formWidget, tableWidget ]
        exclude:
          - entity: conference
            widget: [formWidget, tableWidget]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.15.0'
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/ui/widgets/${{ matrix.entity }}/${{ matrix.widget }}"
          npm install
          npm test
